### PR TITLE
Update django-allauth to 0.34.0 and README.rst

### PR DESCRIPTION
**Pull request by phyxkal**

### CODE REVIEW

**Comment by HargovindArora** [comment]
@phyxkal Can you please squash your commits?! : )

**Comment by phyxkal** [comment]
update django-allauth and README.rst? @HargovindArora

**Comment by HargovindArora** [comment]
Yeah. Can't it be done? Please guide me if I'm wrong somewhere!

**Comment by phyxkal** [comment]
@HargovindArora i dont know, i think no, cause thy are different tasks and different sections, just wait my mentor

**Pull request merged**
