### PR TITLE
 [deps] Update allauth to 0.60.0 #370

### LINKED ISSUE #370: [deps] Update allauth to 0.60.0
Update allauth to 0.60.0. We'll have to make sure tests pass or if not, fix any failing test.

### PR DESCRIPTION
**Pull request by arup1221**
[change] allauth to 0.60.0 #370 

This Pull Request addresses the task of updating the "allauth" package in the project. The package has been upgraded from version 0.54.0 to 0.60.0 to incorporate the latest features, improvements, and bug fixes provided by the upstream maintainers.

Fixes #370

### CODE REVIEW

**Review by nemesifier — CHANGES_REQUESTED** [review]
@arup1221 please check the build failure.

**Comment by arup1221** [comment]
@nemesifier how to re run the workflow?
like my build failed because of 
- missing prefix in the commit short description
  Eg: "[feature/fix/change] Action performed"

**Review by nemesifier — CHANGES_REQUESTED** [review]
@arup1221 it looks like some tests are failing, did you run the tests locally?

**Comment by nemesifier** [comment]
Closing for lack of follow up, thanks for trying :+1:.

**Pull request closed without merging**
