### PR TITLE
[admin] Only organizationuser objects which have admin=True should be able to manage their organization in the admin

### PR DESCRIPTION
**Pull request by oltarzewskik**
GCI task: https://codein.withgoogle.com/dashboard/task-instances/4917403625455616/

### CODE REVIEW

**Comment by OltarzewskiK** [comment]
@nemesisdesign Can you review my code and Am I doing this task in right way?

**Comment by OltarzewskiK** [comment]
@nemesisdesign So should I leave this issue and start working on multitenancy task?
BTW
This function doesn't work: https://github.com/openwisp/openwisp-users/blob/master/openwisp_users/admin.py#L60
and I think that I can handle this function by multitenancy too

**Comment by OltarzewskiK** [comment]
@nemesisdesign I have to move `MultitenantAdminMixin` to `admin.py` or rather to `mixins.py`?

**Comment by nemesisdesign** [comment]
I am closing this PR to clean up the list of outstanding PRs.
Feel free to reopen it in the future if you want to try again.

**Pull request closed without merging**
