### PR TITLE
[change] Removed typographic error for backward compatibility for openwisp-users 0.5 #194

### LINKED ISSUE #194: Remove typographic error for backwards compatibility in openwisp-users 0.5
The typographic error in  this code should be removed in 0.5 release

https://github.com/openwisp/openwisp-users/blob/1ff86e27ffb5764e60c340da234fbcb0507a0aeb/openwisp_users/settings.py#L4-L15

### PR DESCRIPTION
**Pull request by codesankalp**
Removed all the typographic errors for 0.5 release.

Also updated openwisp-utils to 0.7.0 in requirements.txt and
requirements-test.txt

Fixes #194

### CODE REVIEW

**Review by devkapilbansal — COMMENTED** [review]
Thanks @codesankalp for this

**Comment by devkapilbansal** [comment]
@nemesisdesign should be remove this too in this release 
https://github.com/openwisp/openwisp-users/blob/47c68d0805b487317f77130a0bac936500738694/openwisp_users/base/models.py#L63-L80

**Review by pandafy — CHANGES_REQUESTED** [review]
@codesankalp let's not mix things up. @atb00ker is already working for upgrading openwisp-utils dependency in #189 

Please remove the changes for upgrading openiwsp-utils.

**Comment by pandafy** [comment]
@devkapilbansal same applies for you. If that method is something which is planned to be removed in this release, it should be removed in a separate PR. I could not find any issue mentioning that. I request you to create one for taking the discussion further.

**Comment by codesankalp** [comment]
@pandafy Sorry for this time, In future I will keep this in my mind.

**Review by pandafy — APPROVED** [review]
LGTM :+1: 

Requested review from @devkapilbansal
Deferred merging to @atb00ker

**Review by atb00ker — COMMENTED** [review]
Is the next version going to be `0.5.0`? We do minor version upgrade only when there is a backward incompatibility. 
Not sure if I see one since the last release, was this dicussed in the gitter chat room (I might have missed it)?

In either case, can you please add a note in the `CHANGES.rst` about a backward incompatibility? :smile:
EXAMPLE:
In `0.4.0` release, there is a `**backward incompatible change**` notice in bold! 😄 
Example:

**Comment by pandafy** [comment]
> Is the next version going to be `0.5.0`?

@atb00ker please see #195, there is more to it than this change.

**Comment by atb00ker** [comment]
Thanks @pandafy ! 😊

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1:

**Comment by devkapilbansal** [comment]
> @devkapilbansal same applies for you. If that method is something which is planned to be removed in this release, it should be removed in a separate PR. I could not find any issue mentioning that. I request you to create one for taking the discussion further.

@pandafy Opened #197 for this

**Review by nemesisdesign — APPROVED** [review]

**Pull request merged**
