### PR TITLE
[chores] Formatted code with new black version

### PR DESCRIPTION
**Pull request by pandafy**

### CODE REVIEW

**Review by devkapilbansal — APPROVED** [review]

**Review by devkapilbansal — COMMENTED** [review]
@pandafy
Shouldn't we change the version in `requirements` file instead of `requirements-test` if both need `openwisp-utils'

**Comment by nemesisdesign** [comment]
@devkapilbansal main requirements already point to utils dev: https://github.com/openwisp/openwisp-users/blob/master/requirements.txt#L6-L7

**Review by nemesisdesign — APPROVED** [review]

**Comment by devkapilbansal** [comment]
> @devkapilbansal main requirements already point to utils dev: https://github.com/openwisp/openwisp-users/blob/master/requirements.txt#L6-L7

I mean, we can leave it unpinned too 🤔

**Comment by pandafy** [comment]
> > @devkapilbansal main requirements already point to utils dev: https://github.com/openwisp/openwisp-users/blob/master/requirements.txt#L6-L7
> 
> I mean, we can leave it unpinned too thinking

I don't understand your comment completely, but unpinning it in requirement.txt will affect installation of modules, e.g. when modules are installed by dev branch of ansible-openwisp2. 

requirements-test.txt is only used for development.

**Pull request merged**
